# Change these first
owner: Project-And-Factory # Your GitHub organization or username, where this repository lives
repo: Uptime # The name of this repository

sites:
  - name: Main Website
    url: https://pafgroup.org
  - name: Project And Factory API
    url: https://api.pafgroup.org
  - name: PiglinBBS
    url: https://www.piglinbbs.com/images/1.jpg
  - name: Blog
    url: https://blog.pafgroup.org/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: ganyustatus.live
  # baseUrl: /your-repo-name
  logoUrl: https://files.pafgroup.org/103430917_p1.jpg
  name: Ganyu Status Dashboard
  introTitle: "Ganyu Status Dashboard"
  introMessage: This shows the running status of all Project And Factory services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
